FROM node:14 AS build

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build

FROM node:14

WORKDIR /usr/src/app

RUN npm install -g serve

COPY --from=build /usr/src/app/build ./build

CMD ["serve", "-s", "build"]

EXPOSE 3000